Add post-latch registration step
Handle registration failure gracefully by printing information in an additional step.

Add a new output that flags if the workflow was already registered.

Add a new input option to not fail if the workflow was already registered.

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -39,17 +39,21 @@ inputs:
     description: "Whether to automatically bump the version of the workflow each time register is called."
     required: false
     default: false
-
+  already-registered-do-not-fail:
+    description: "Whether the workflow should fail if the worfklow is already registered."
+    required: false
+    default: false
 
 outputs:
   latch-version:
     description: "The installed latch version."
     value: ${{ steps.latch-version.outputs.latch-version }}
   register-version:
-    description: "The workflow version that was registered"
+    description: "The workflow version that was registered.  Only set when 'inputs.register' is 'true'."
     value: ${{ steps.latch-register.outputs.register-version }}
-
-
+  already-registered:
+    description: "'true' if the workflow was already registered, 'false' otherwise.  Only set when 'inputs.register' is 'true'."
+    value: ${{ steps.after-latch-register.outputs.already-registered }}
 runs:
   using: "composite"
   steps:
@@ -88,6 +92,7 @@ runs:
     - id: latch-register
       if: ${{ inputs.register == 'true' }}
       shell: bash
+      continue-on-error: true
       run: |
           eval `ssh-agent -s`
           args="${{ inputs.register-pkg-root }}"
@@ -97,7 +102,63 @@ runs:
           if [ "${{ inputs.register-register-disable-auto-version }}" == "true" ]; then
             args="--register-disable-auto-version ${args}"
           fi
-          latch register --yes ${args} 2>&1 | tee register.log  
+          latch register --yes ${args} 2>&1 | tee register.log
+          # save registered version; this may not occur if the above register fails
           register_version=$(grep "Registering" register.log | tail -1 | cut -f 2 -d ' ' | cut -f 2 -d ':')
           echo "register-version=${register_version}" >> $GITHUB_OUTPUT
-          echo Registered version "${register_version}".
+    - id: after-latch-register
+      if: (${{ inputs.register == 'true' }})
+      shell: bash
+      run: |
+          # Deal with successful registration
+          if [[ "${{ steps.latch-register.outcome }}" == "success" ]]; then
+             echo Registered version ${{ steps.latch-register.outputs.latch-version }}
+             echo "already-registered=false" >> $GITHUB_OUTPUT
+             exit 0
+          fi
+      
+          # Deal with registration failure
+          spacer_line="------------------------------------------------------------"; 
+          already_registered="false"
+          
+          # Print environment information (e.g. installed latch version, OS, etc.)
+          if [ -f .latch-report.tag.gz ]; then
+            echo "Printing environment information:"
+            tar -Ozxvf .latch_report.tar.gz metadata.json 2>/dev/null
+          else
+            echo "No .latch_report.tag.gz found! Continuing..."
+          fi  
+          
+          # Find the line in the log to start printing from.
+          pattern="Unable to register workflow";
+          result=$(grep "${pattern}" "register.log" || echo "");
+          echo -e "${spacer_line}"
+          echo "Printing error traceback:"
+          if [[ "${result}" == "" ]]; then
+            # If no such line exists, then just print the last forty lines
+            tail -n 40 "register.log";
+            echo -e "${spacer_line}"
+            echo "Unknown error!"
+          else
+            # Print error information
+            sed -n "/${pattern}/"',$p' "register.log"
+            echo -e "${spacer_line}"
+            echo -n "Error: "
+            tail -4 "register.log" | head -1 | cut -f 2- -d ' '
+          fi
+          
+          # check if already registered
+          pattern="has already been registered."
+          result=$(grep "${pattern}" "register.log" || echo "");
+          if [[ "${result}" != "" ]]; then
+            already_registered="true"
+          fi
+          # save result
+          echo "already-registered=${already_registered}" >> $GITHUB_OUTPUT
+          # check if we should fail when the image was already registered
+          if [[ "${{ inputs.already-registered-do-not-fail }}" == "true" ]] && [[ "${already_registered}" == "true" ]]; then
+            exit 0;
+          fi
+          # fail otherwise
+          exit 1
+
