chore: add banner, better logging, and log grouping (#23)
* chore: add banner, better logging, and log grouping

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -57,49 +57,67 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - id: print-banner
+      name: Print Banner
+      shell: bash
+      run: |
+        cat ./banner.txt
     - id: setup-ssh-config
       name: Setup SSH Config
       if: ${{ inputs.ssh-config == 'true' }}
       shell: bash
       run: |
+        echo "::group::Setting up SSH config...🚦"
         mkdir -p ~/.ssh
         echo 'Host *' >> ~/.ssh/config
         echo '    StrictHostKeyChecking no' >> ~/.ssh/config
         chmod 600 ~/.ssh/config
+        echo "::endgroup::"
     - id: setup-workspace
       name: Setup the Latch Workspace
       if: ${{ inputs.latch-workspace != '' }}
       shell: bash
       run: |
+        echo "::group::Setting up latch workspace...🚦"
         mkdir -p ~/.latch
         echo -n "${{ inputs.latch-workspace }}" > ~/.latch/workspace
+        echo "::endgroup::"
     - id: setup-token
       name: Setup the Latch Token
       if: ${{ inputs.latch-token != '' }}
       shell: bash
       run: |
+        echo "::group::Setting up latch token...🚦"
         mkdir -p ~/.latch
         echo -n "${{ inputs.latch-token }}" > ~/.latch/token
+        echo "::endgroup::"
     - id: install-latch
       name: Install Latch
       shell: bash
       run: |
+        echo "::group::Installing latch...🚦"
         if [ "latest" == "${{ inputs.latch-version }}" ]; then
           python3 -m pip install --upgrade latch
         else
           python3 -m pip install latch==${{ inputs.latch-version }}
         fi
+        echo "::endgroup::"
     - id: latch-version
       name: Get the installed Latch version
       shell: bash
       run: |
-        echo "latch-version=$(latch --version | cut -f 3 -d ' ')" >> $GITHUB_OUTPUT
+        echo "::group::Getting installed latch version...🚦"
+        LATCH_VERSION=$(latch --version | cut -f 3 -d ' ')
+        echo "latch-version=${LATCH_VERSION}" >> $GITHUB_OUTPUT
+        echo "latch version: ${LATCH_VERSION}"
+        echo "::endgroup::"
     - id: latch-register
       name: Register the Workflow on Latch
       if: ${{ inputs.register == 'true' }}
       shell: bash
       continue-on-error: true
       run: |
+          echo "::group::Registering workflow 🚦"
           eval `ssh-agent -s`
           args="${{ inputs.register-pkg-root }}"
           if [ "${{ inputs.register-remote }}" == "true" ]; then
@@ -112,6 +130,7 @@ runs:
           # save registered version; this may not occur if the above register fails
           register_version=$(grep "Registering" register.log | tail -1 | awk '{print $NF}' | cut -f 2 -d ':')
           echo "register-version=${register_version}" >> $GITHUB_OUTPUT
+          echo "::endgroup::"
     - id: after-latch-register
       name: Post-process Latch Workflow Registration
       if: ${{ inputs.register == 'true' }}
@@ -119,7 +138,7 @@ runs:
       run: |
           # Deal with successful registration
           if [[ "${{ steps.latch-register.outcome }}" == "success" ]]; then
-             echo Registered version ${{ steps.latch-register.outputs.register-version }}
+             echo "Registered version ${{ steps.latch-register.outputs.register-version }}! ✅"
              echo "already-registered=false" >> $GITHUB_OUTPUT
              exit 0
           fi
@@ -130,10 +149,11 @@ runs:
           
           # Print environment information (e.g. installed latch version, OS, etc.)
           if [ -f .latch-report.tar.gz ]; then
-            echo "Printing environment information:"
+            echo "::group::Printing environment information! ℹ️ "
             tar -Ozxvf .latch_report.tar.gz metadata.json 2>/dev/null
+            echo "::endgroup::"
           else
-            echo "No .latch_report.tar.gz found! Continuing..."
+            echo "No .latch_report.tar.gz found‼️ Continuing..."
           fi  
           # Turn this off so grep works
           set +eo pipefail
@@ -141,12 +161,12 @@ runs:
           pattern="Unable to register workflow";
           result=$(grep "${pattern}" "register.log" || echo "");
           echo -e "${spacer_line}"
-          echo "Printing error traceback:"
+          echo "::group::Printing error traceback"
           if [[ "${result}" == "" ]]; then
             # If no such line exists, then just print the last forty lines
             tail -n 40 "register.log";
             echo -e "${spacer_line}"
-            echo "Unknown error!"
+            echo "Unknown error‼️"
           else
             # Print error information
             sed -n "/${pattern}/"',$p' "register.log"
@@ -154,6 +174,7 @@ runs:
             echo -n "Error: "
             tail -4 "register.log" | head -1 | cut -f 2- -d ' '
           fi
+          echo "::endgroup::"
           
           # check if already registered
           pattern="has already been registered."
@@ -164,9 +185,16 @@ runs:
           # save result
           echo "already-registered=${already_registered}" >> $GITHUB_OUTPUT
           # check if we should fail when the image was already registered
-          if [[ "${{ inputs.already-registered-do-not-fail }}" == "true" ]] && [[ "${already_registered}" == "true" ]]; then
-            exit 0;
+          if [[ "${already_registered}" == "true" ]]; then
+            if [[ "${{ inputs.already-registered-do-not-fail }}" == "true" ]]; then
+              echo "Already registered! ✅"
+              exit 0;
+            else
+              echo "Already registered! ❌"
+              exit 1
+            fi
           fi
           # fail otherwise
+          echo "Registration failed! See above for details... ❌"
           exit 1
 
